[project]
name = "web_service"
version = "0.2.0"
description = "Unicorn Properties Web Service"
authors = [
    {name = "Amazon Web Services"}
]
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "aws-lambda-powertools[tracer]>=3.25.0",
    "aws-xray-sdk>=2.15.0",
    "boto3>=1.42.68",
    "requests>=2.32.5",
    "crhelper>=2.0.12",
]

[project.optional-dependencies]
dev = [
    "aws-lambda-powertools[all]>=3.25.0",
    "moto[dynamodb,events,sqs]>=5.1.22",
    "importlib-metadata>=8.7.1",
    "pyyaml>=6.0.3",
    "arnparse>=0.0.2",
    "pytest>=9.0.2",
    "pytest-cov>=6.1.1",
    "ruff>=0.15.6",
]

[tool.setuptools]
package-dir = {"web_service" = "src"}
packages = ["web_service"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -vv -W ignore::UserWarning --cov=src --cov-report=term-missing --cov-fail-under=80"
testpaths = ["tests/unit", "tests/integration"]
pythonpath = ["src"]

[tool.coverage.run]
omit = ["*/schema/*"]
