# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
Description: >
  Unicorn Contracts Service - A serverless microservice for managing property contracts
  with event-driven architecture. Features REST API with async SQS processing, DynamoDB 
  storage with change data capture, and EventBridge integration for real-time domain 
  event publishing. Includes comprehensive observability with AWS Powertools, 
  and dead letter queues for reliable message processing.

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - ES4000 # Rule disabled because the CatchAll Rule doesn't need a DLQ
        - ES6000 # Rule disabled because SQS DLQs don't need a RedrivePolicy
        - WS2001 # Rule disabled because check does not support !ToJsonString transform
        - ES1001 # Rule disabled because our Lambda functions don't need DestinationConfig.OnFailure
        - W3002 # Rule disabled as nested templates are being packaged

Parameters:
  Stage:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - prod

Mappings:
  LogsRetentionPeriodMap:
    local:
      Days: 3
    dev:
      Days: 3
    prod:
      Days: 14
  Constants:
    ProjectName:
      Value: "AWS Serverless Developer Experience"

Conditions:
  IsProd: !Equals [!Ref Stage, prod]

Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Runtime: python3.12
    MemorySize: 512
    Timeout: 15
    Tracing: Active
    Architectures:
      - x86_64
    Environment:
      Variables:
        DYNAMODB_TABLE: !Ref ContractsTable
        SERVICE_NAMESPACE: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"
        POWERTOOLS_SERVICE_NAME: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"
        POWERTOOLS_TRACE_DISABLED: "false" # Explicitly disables tracing, default
        POWERTOOLS_LOGGER_LOG_EVENT: !If [IsProd, "false", "true"] # Logs incoming event, default
        POWERTOOLS_LOGGER_SAMPLE_RATE: !If [IsProd, "0.1", "0"] # Debug log sampling percentage, default
        POWERTOOLS_METRICS_NAMESPACE: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"
        POWERTOOLS_LOG_LEVEL: INFO # Log level for Logger (INFO, DEBUG, etc.), default
        LOG_LEVEL: INFO # Log level for Logger
    Tags:
      stage: !Ref Stage
      project: !FindInMap [Constants, ProjectName, Value]
      namespace: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"

Resources:
  #################################################################################################
  #### LAMBDA FUNCTIONS
  #### Core business logic for contract management and processing
  #################################################################################################

  # Event-driven function that processes contract operations from API Gateway via SQS
  # Handles CRUD operations on contracts and publishes domain events for downstream services
  ContractEventHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../src/
      Handler: contracts_service.contract_event_handler.lambda_handler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref ContractsTable
        - DynamoDBReadPolicy:
            TableName: !Ref ContractsTable
      Events:
        IngestQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt UnicornContractsIngestQueue.Arn
            BatchSize: 1
            Enabled: true
            ScalingConfig:
              MaximumConcurrency: 5

  # CloudWatch log group for contract event handler with environment-specific retention
  ContractEventHandlerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ContractEventHandlerFunction}"
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  #################################################################################################
  #### API GATEWAY REST API
  #### RESTful interface for contract management with async processing via SQS integration
  #################################################################################################

  # Main REST API for contract operations with SQS integration for reliable async processing
  # Provides endpoints for creating, updating, and retrieving contract information
  UnicornContractsApi:
    Type: AWS::Serverless::Api
    DependsOn: ContractsApiGwAccountConfig
    Properties:
      StageName: !Ref Stage
      EndpointConfiguration:
        Type: REGIONAL
      TracingEnabled: true
      MethodSettings:
        - MetricsEnabled: true
          ResourcePath: /*
          HttpMethod: "*"
          LoggingLevel: !If [IsProd, ERROR, INFO]
          ThrottlingBurstLimit: 10
          ThrottlingRateLimit: 100
      AccessLogSetting:
        DestinationArn: !GetAtt UnicornContractsApiLogGroup.Arn
        Format: >
          {"requestId": $context.requestId, "integration-error": $context.integration.error, "integration-status": $context.integration.status, "integration-latency": $context.integration.latency, "integration-requestId": $context.integration.requestId, "integration-integrationStatus": $context.integration.integrationStatus, "response-latency": $context.responseLatency, "status": $context.status}
      DefinitionBody: !Transform
        Name: "AWS::Include"
        Parameters:
          Location: "api.yaml"
      Tags:
        stage: !Ref Stage
        project: !FindInMap [Constants, ProjectName, Value]
        namespace: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"

  # CloudWatch log group for API Gateway access logs and performance metrics
  UnicornContractsApiLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  # Global API Gateway account configuration required for CloudWatch logging
  ContractsApiGwAccountConfig:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt UnicornContractsApiGwAccountConfigRole.Arn

  # IAM role that allows API Gateway to write logs to CloudWatch
  UnicornContractsApiGwAccountConfigRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: apigateway.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  # IAM role that enables API Gateway to send messages directly to SQS
  # Implements async processing pattern for reliable request handling
  UnicornContractsApiIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: apigateway.amazonaws.com
      Policies:
        - PolicyName: AllowSqsIntegration
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                Resource: !GetAtt UnicornContractsIngestQueue.Arn

  #################################################################################################
  #### MESSAGING & INTEGRATION
  #### SQS queues and EventBridge components for reliable async processing and event publishing
  #################################################################################################

  # Primary ingestion queue that decouples API Gateway from Lambda processing
  # Enables reliable async processing with built-in retry and DLQ capabilities
  UnicornContractsIngestQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      SqsManagedSseEnabled: true
      MessageRetentionPeriod: 1209600 # Maximum value, 1,209,600 (14days)
      QueueName: !Sub UnicornContractsIngestQueue-${Stage}
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt UnicornContractsIngestDLQ.Arn
        maxReceiveCount: 1
      VisibilityTimeout: 20
      Tags:
        - Key: stage
          Value: !Ref Stage
        - Key: project
          Value: !FindInMap [Constants, ProjectName, Value]
        - Key: namespace
          Value: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"

  # DLQ for messages that fail processing after retry attempts
  # Critical for debugging processing failures and ensuring no data loss
  UnicornContractsIngestDLQ:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      SqsManagedSseEnabled: true
      MessageRetentionPeriod: 1209600 # Maximum value, 1,209,600 (14days)
      QueueName: !Sub UnicornContractsIngestDLQ-${Stage}
      Tags:
        - Key: stage
          Value: !Ref Stage
        - Key: project
          Value: !FindInMap [Constants, ProjectName, Value]
        - Key: namespace
          Value: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"

  # Development and debugging rule that captures all contract domain events
  # Useful for monitoring event flow and troubleshooting integration issues
  UnicornContractsCatchAllRule:
    Type: AWS::Events::Rule
    Properties:
      Name: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}-CatchAllEvents"
      Description: Catch all events published by the Contracts service.
      EventBusName: !Sub "{{resolve:ssm:/uni-prop/${Stage}/ContractsEventBus}}"
      EventPattern:
        account:
          - !Ref AWS::AccountId
        source:
          - "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"
      State: ENABLED #You may want to disable this rule in production
      Targets:
        - Arn: !GetAtt UnicornContractsCatchAllLogGroup.Arn
          Id: !Sub UnicornContractsCatchAllLogGroupTarget-${Stage}

  # CloudWatch log group for the catchall rule - stores all contract events for debugging
  UnicornContractsCatchAllLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub
        - "/aws/events/${Stage}/${NS}-catchall"
        - Stage: !Ref Stage
          NS: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"
      RetentionInDays: !FindInMap
        - LogsRetentionPeriodMap
        - !Ref Stage
        - Days

  # Resource policy that grants EventBridge permission to write to CloudWatch Logs
  # Required for the catchall rule to function properly
  EventBridgeCloudWatchLogGroupPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: !Sub EvBToCWLogs-${AWS::StackName}
      # Note: PolicyDocument has to be established this way. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-resourcepolicy.html#cfn-logs-resourcepolicy-policydocument
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "delivery.logs.amazonaws.com",
                  "events.amazonaws.com"
                ]
              },
              "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": [
                "${UnicornContractsCatchAllLogGroup.Arn}"
              ]
            }
          ]
        }

  #### EVENT BRIDGE PIPES
  # EventBridge Pipe that transforms DynamoDB stream records into domain events
  # Automatically publishes ContractStatusChanged events when contract status changes
  # Main pipe that converts DynamoDB changes to structured domain events
  # Filters for DRAFT and APPROVED status changes and transforms data for downstream consumers
  ContractsTableStreamToEventPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      RoleArn: !GetAtt ContractsTableStreamToEventPipeRole.Arn
      Source: !GetAtt ContractsTable.StreamArn
      SourceParameters:
        DynamoDBStreamParameters:
          MaximumRetryAttempts: 3
          BatchSize: 1
          StartingPosition: LATEST
          DeadLetterConfig:
            Arn: !GetAtt ContractsTableStreamToEventPipeDLQ.Arn
        FilterCriteria:
          Filters:
            - Pattern: >-
                {"eventName":["INSERT","MODIFY"],"dynamodb":{"NewImage":{"contract_status":{"S":["DRAFT","APPROVED"]}}}}
      LogConfiguration:
        CloudwatchLogsLogDestination:
          LogGroupArn: !GetAtt ContractsTableStreamToEventPipeLogGroup.Arn
        Level: ERROR
      TargetParameters:
        EventBridgeEventBusParameters:
          DetailType: ContractStatusChanged
          Source: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"
        InputTemplate: |-
          {
            "property_id": "<$.dynamodb.Keys.property_id.S>",
            "contract_id": "<$.dynamodb.NewImage.contract_id.S>",
            "contract_status": "<$.dynamodb.NewImage.contract_status.S>",
            "contract_last_modified_on": "<$.dynamodb.NewImage.contract_last_modified_on.S>"
          }
      Target: !Sub "{{resolve:ssm:/uni-prop/${Stage}/ContractsEventBusArn}}"

  # CloudWatch log group for EventBridge Pipe execution logs and error tracking
  ContractsTableStreamToEventPipeLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  # IAM role that grants EventBridge Pipe permissions to read DynamoDB streams and publish events
  # Includes access to DLQ for failed transformations
  ContractsTableStreamToEventPipeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: pipes.amazonaws.com
          Condition:
            StringEquals:
              aws:SourceAccount: !Ref AWS::AccountId
      Policies:
        - PolicyName: ContractsTableStreamToEventPipePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:ListStreams
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !GetAtt ContractsTable.StreamArn
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: !Sub "{{resolve:ssm:/uni-prop/${Stage}/ContractsEventBusArn}}"
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt ContractsTableStreamToEventPipeDLQ.Arn

  # DLQ for EventBridge Pipe failures - captures records that fail transformation or delivery
  # Essential for debugging event publishing issues and ensuring data integrity
  ContractsTableStreamToEventPipeDLQ:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      SqsManagedSseEnabled: true
      MessageRetentionPeriod: 1209600 # Maximum value, 1,209,600 (14days)
      QueueName: !Sub ContractsTableStreamToEventPipeDLQ-${Stage}
      Tags:
        - Key: stage
          Value: !Ref Stage
        - Key: project
          Value: !FindInMap [Constants, ProjectName, Value]
        - Key: namespace
          Value: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"

  #################################################################################################
  #### DYNAMODB TABLE
  #### Primary data store for contract information with change data capture via streams
  #################################################################################################

  # Main data store for contract information with DynamoDB Streams enabled
  # Streams trigger EventBridge Pipe for real-time event publishing to downstream services
  ContractsTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: property_id
          AttributeType: S
      KeySchema:
        - AttributeName: property_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: stage
          Value: !Ref Stage
        - Key: project
          Value: !FindInMap [Constants, ProjectName, Value]
        - Key: namespace
          Value: "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"

Outputs:
  #### API GATEWAY OUTPUTS
  BaseUrl:
    Description: Web service API endpoint
    Value: !Sub "https://${UnicornContractsApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}"
  ApiUrl:
    Description: Contract service API endpoint
    Value: !Sub "https://${UnicornContractsApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${Stage}/"

  #### SQS OUTPUTS
  IngestQueueUrl:
    Description: URL for the Ingest SQS Queue
    Value: !GetAtt UnicornContractsIngestQueue.QueueUrl

  #### DYNAMODB OUTPUTS
  ContractsTableName:
    Description: DynamoDB table storing contract information
    Value: !Ref ContractsTable

  #### LAMBDA FUNCTIONS OUTPUTS
  ContractEventHandlerFunctionName:
    Description: ContractEventHandler function name
    Value: !Ref ContractEventHandlerFunction
  ContractEventHandlerFunctionArn:
    Description: ContractEventHandler function ARN
    Value: !GetAtt ContractEventHandlerFunction.Arn

  #### CLOUDWATCH LOGS OUTPUTS
  UnicornContractsCatchAllLogGroupArn:
    Description: Log all events on the service's EventBridge Bus
    Value: !GetAtt UnicornContractsCatchAllLogGroup.Arn
