[project]
name = "approvals_service"
version = "0.2.0"
description = "Unicorn Properties Property Service"
authors = [
    {name = "Amazon Web Services"}
]
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "aws-lambda-powertools[tracer]>=3.31.0",
    "aws-xray-sdk>=2.15.0",
    "boto3>=1.43.40",
]

[project.optional-dependencies]
dev = [
    "aws-lambda-powertools[all]>=3.31.0",
    "requests>=2.34.2",
    "moto[dynamodb,events,sqs]>=5.2.2",
    "importlib-metadata>=9.0.0",
    "pyyaml>=6.0.3",
    "arnparse>=0.0.2",
    "pytest>=9.1.1",
    "ruff>=0.15.20",
]

[tool.setuptools]
package-dir = {"approvals_service" = "src"}
packages = ["approvals_service"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -vv -W ignore::UserWarning"
testpaths = ["tests/unit", "tests/integration"]
pythonpath = ["."]
