# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: >
  Unicorn Contracts Service resources.

#### METADATA
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - I3042
        - ES1007
        - ES1001
        - WS2001

#### PARAMETERS
Parameters:
  Stage:
    Type: String
    Default: Local
    AllowedValues:
      - Local
      - Dev
      - Prod

#### MAPPINGS
Mappings:
  LogsRetentionPeriodMap:
    Local:
      Days: 3
    Dev:
      Days: 3
    Prod:
      Days: 14
  Constants:
    ServiceNamespace:
      Value: "unicorn.contracts"
    ProjectName:
      Value: "AWS Serverless Developer Experience"

#### CONDITIONS
Conditions:
  IsProd: !Equals [!Ref Stage, Prod]

#### GLOBALS
Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Runtime: python3.11
    MemorySize: 128
    Timeout: 3
    Tracing: Active
    Architectures:
      - x86_64
    Environment:
      Variables:
        DYNAMODB_TABLE: !Ref ContractsTable
        SERVICE_NAMESPACE: !FindInMap [Constants, ServiceNamespace, Value]
        POWERTOOLS_SERVICE_NAME: !FindInMap [Constants, ServiceNamespace, Value]
        POWERTOOLS_TRACE_DISABLED: "false" # Explicitly disables tracing, default
        POWERTOOLS_LOGGER_LOG_EVENT: !If [IsProd, "false", "true"] # Logs incoming event, default
        POWERTOOLS_LOGGER_SAMPLE_RATE: !If [IsProd, "0.1", "0"] # Debug log sampling percentage, default
        POWERTOOLS_METRICS_NAMESPACE: !FindInMap [
            Constants,
            ServiceNamespace,
            Value,
          ] # Metric Namespace
        LOG_LEVEL: INFO # Log level for Logger (INFO, DEBUG, etc.), default
    Tags:
      stage: !Ref Stage
      project: !FindInMap [Constants, ProjectName, Value]
      namespace: !FindInMap [Constants, ServiceNamespace, Value]

#### RESOURCES
Resources:
  #### SSM PARAMETERS
  # Services own and share their namespace
  UnicornContractsNamespaceParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /UniProp/${Stage}/UnicornContractsNamespace
      Value: !FindInMap [Constants, ServiceNamespace, Value]

  # Services share their event bus name and arn
  UnicornContractsEventBusNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /UniProp/${Stage}/UnicornContractsEventBus
      Value: !GetAtt UnicornContractsEventBus.Name

  UnicornContractsEventBusArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /UniProp/${Stage}/UnicornContractsEventBusArn
      Value: !GetAtt UnicornContractsEventBus.Arn

  #### LAMBDA FUNCTIONS
  ContractEventHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: contracts_service.contract_event_handler.lambda_handler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref ContractsTable
        - DynamoDBReadPolicy:
            TableName: !Ref ContractsTable
      # Events:
      #   IngestQueue:
      #     Type: SQS
      #     Properties:
      #       Queue: !GetAtt UnicornContractsIngestQueue.Arn
      #       BatchSize: 1
      #       Enabled: true
      #       ScalingConfig:
      #         MaximumConcurrency: 5

  ContractEventHandlerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ContractEventHandlerFunction}"
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  #### API GATEWAY REST API
  UnicornContractsApi:
    Type: AWS::Serverless::Api
    DependsOn: ContractsApiGwAccountConfig
    Properties:
      StageName: !Ref Stage
      EndpointConfiguration:
        Type: REGIONAL
      TracingEnabled: true
      MethodSettings:
        - MetricsEnabled: true
          ResourcePath: /*
          HttpMethod: "*"
          LoggingLevel: !If [IsProd, ERROR, INFO]
          ThrottlingBurstLimit: 10
          ThrottlingRateLimit: 100
      AccessLogSetting:
        DestinationArn: !GetAtt UnicornContractsApiLogGroup.Arn
        Format: !ToJsonString
          requestId: $context.requestId
          integration-error: $context.integration.error
          integration-status: $context.integration.status
          integration-latency: $context.integration.latency
          integration-requestId: $context.integration.requestId
          integration-integrationStatus: $context.integration.integrationStatus
          response-latency: $context.responseLatency
          status: $context.status
      DefinitionBody: !Transform
        Name: "AWS::Include"
        Parameters:
          Location: "api.yaml"
      Tags:
        stage: !Ref Stage
        project: !FindInMap [Constants, ProjectName, Value]
        namespace: !FindInMap [Constants, ServiceNamespace, Value]

  ContractsApiGwAccountConfig:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt UnicornContractsApiGwAccountConfigRole.Arn

  # API GW IAM roles
  ContractsApiIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: apigateway.amazonaws.com
      Policies:
        - PolicyName: AllowSqsIntegration
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                Resource: !GetAtt UnicornContractsIngestQueue.Arn

  # API GW Cloudwatch Log Group
  UnicornContractsApiLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  UnicornContractsApiGwAccountConfigRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  #### INGEST QUEUES
  UnicornContractsIngestQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      SqsManagedSseEnabled: true
      MessageRetentionPeriod: 1209600 # Maximum value, 1,209,600 (14days)
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt UnicornContractsIngestDLQ.Arn
        maxReceiveCount: 1
      VisibilityTimeout: 20
      Tags:
        - Key: stage
          Value: !Ref Stage
        - Key: project
          Value: !FindInMap [Constants, ProjectName, Value]
        - Key: namespace
          Value: !FindInMap [Constants, ServiceNamespace, Value]

  UnicornContractsIngestDLQ:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - ES6000
    Properties:
      SqsManagedSseEnabled: true
      MessageRetentionPeriod: 1209600 # Maximum value, 1,209,600 (14days)
      Tags:
        - Key: stage
          Value: !Ref Stage
        - Key: project
          Value: !FindInMap [Constants, ProjectName, Value]
        - Key: namespace
          Value: !FindInMap [Constants, ServiceNamespace, Value]

  #### DYNAMODB TABLE
  ContractsTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: property_id
          AttributeType: S
      KeySchema:
        - AttributeName: property_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: project
          Value: !FindInMap [Constants, ProjectName, Value]
        - Key: namespace
          Value: !FindInMap [Constants, ServiceNamespace, Value]
        - Key: stage
          Value: !Ref Stage

  #### EVENT BUS
  # Event bus for Contract Service used to publish and consume events
  UnicornContractsEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub UnicornContractsBus-${Stage}

  # Event bus policy to restrict who can publish events (should only be services from ServiceNamespace)
  ContractEventsBusPublishPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref UnicornContractsEventBus
      StatementId: !Sub ContactsPublishEventsPolicy-${Stage}
      Statement:
        Effect: Allow
        Principal:
          AWS:
            - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
        Action:
          - events:PutEvents
        Resource: !GetAtt UnicornContractsEventBus.Arn
        Condition:
          StringEquals:
            events:source:
              - !FindInMap [Constants, ServiceNamespace, Value]

  # Catchall rule used for development purposes.
  UnicornContractsCatchAllRule:
    Type: AWS::Events::Rule
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - ES4000
    Properties:
      Name: contracts.catchall
      Description: Catch all events published by the contracts service.
      EventBusName: !Ref UnicornContractsEventBus
      EventPattern:
        source:
          - prefix: ""
      State: ENABLED #You may want to disable this rule in production
      Targets:
        - Arn: !GetAtt UnicornContractsCatchAllLogGroup.Arn
          Id: !Sub UnicornContractsCatchAllLogGroupTarget-${Stage}

  # CloudWatch log group used to catch all events
  UnicornContractsCatchAllLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  # Permissions to allow EventBridge to send logs to CloudWatch
  EventBridgeCloudWatchLogGroupPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: !Sub UnicornContracts-EventBridgeToCWLogsPolicy-${Stage}
      # Note: PolicyDocument has to be established this way. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-resourcepolicy.html#cfn-logs-resourcepolicy-policydocument
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "delivery.logs.amazonaws.com",
                  "events.amazonaws.com"
                ]
              },
              "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": [
                "${UnicornContractsCatchAllLogGroup.Arn}"
              ]
            }
          ]
        }

  #### EVENT BRIDGE PIPES
  # Pipe changed on DynamoDB Table to UnicornContractsEventBus
  DdbStreamToEventPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      RoleArn: !GetAtt DdbStreamToEventPipeRole.Arn
      Source: !GetAtt ContractsTable.StreamArn
      SourceParameters:
        DynamoDBStreamParameters:
          StartingPosition: LATEST
          OnPartialBatchItemFailure: AUTOMATIC_BISECT
          BatchSize: 1
          # DeadLetterConfig:
          #   Arn: String
        FilterCriteria:
          Filters:
            - Pattern: !ToJsonString
                eventName: [INSERT, MODIFY]
                dynamodb:
                  NewImage:
                    contract_status:
                      S: [DRAFT, APPROVED]
      # Enrichment: arn:aws:execute-api:us-east-1:123456789123:53eo2i89p9/*/POST/pets
      Target: !GetAtt UnicornContractsEventBus.Arn
      TargetParameters:
        EventBridgeEventBusParameters:
          Source: !FindInMap [Constants, ServiceNamespace, Value]
          DetailType: ContractStatusChanged
        InputTemplate: !ToJsonString
          property_id: "<$.dynamodb.NewImage.property_id.S>"
          contract_id: "<$.dynamodb.NewImage.contract_id.S>"
          contract_status: "<$.dynamodb.NewImage.contract_status.S>"
          contract_last_modified_on: "<$.dynamodb.NewImage.contract_last_modified_on.S>"

  # IAM Role for Event Bridge Pipe
  DdbStreamToEventPipeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: pipes.amazonaws.com
      Policies:
        - PolicyName: AllowDdbStreamRead
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:ListStreams
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                Resource: !GetAtt ContractsTable.StreamArn
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: !GetAtt UnicornContractsEventBus.Arn

#### OUTPUTS
Outputs:
  BaseUrl:
    Description: Web service API endpoint
    Value: !Sub "https://${UnicornContractsApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}"
  ApiUrl:
    Description: Contract service API endpoint
    Value: !Sub "https://${UnicornContractsApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${Stage}/"

  IngestQueueUrl:
    Description: URL for the Ingest SQS Queue
    Value: !GetAtt UnicornContractsIngestQueue.QueueUrl

  ContractsTableName:
    Description: DynamoDB table storing contract information
    Value: !Ref ContractsTable

  ContractEventHandlerFunctionArn:
    Description: Create Contract function ARN
    Value: !GetAtt ContractEventHandlerFunction.Arn

  IsProd:
    Description: Is Production?
    Value: !If [IsProd, "true", "false"]
