# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: '2010-09-09'
Description: Event Schemas for use by the Properties Service

Parameters:
  Stage:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - prod

Resources:
  EventRegistry:
    Type: AWS::EventSchemas::Registry
    Properties: 
      Description: 'Event schemas for Unicorn Properties'
      RegistryName: !Sub "{{resolve:ssm:/uni-prop/${Stage}/UnicornPropertiesNamespace}}"

  EventRegistryPolicy:
    Type: AWS::EventSchemas::RegistryPolicy
    Properties: 
      RegistryName: !GetAtt EventRegistry.RegistryName
      Policy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowExternalServices
            Effect: Allow
            Principal:
              AWS:
                - !Ref AWS::AccountId
            Action:
              - schemas:DescribeCodeBinding
              - schemas:DescribeRegistry
              - schemas:DescribeSchema
              - schemas:GetCodeBindingSource
              - schemas:ListSchemas
              - schemas:ListSchemaVersions
              - schemas:SearchSchemas
            Resource:
              - !GetAtt EventRegistry.RegistryArn
              - !Sub "arn:${AWS::Partition}:schemas:${AWS::Region}:${AWS::AccountId}:schema/${EventRegistry.RegistryName}*"

  PublicationEvaluationCompleted:
    Type: AWS::EventSchemas::Schema
    Properties:
      Type: 'OpenApi3'
      RegistryName: !GetAtt EventRegistry.RegistryName
      SchemaName: !Sub '${EventRegistry.RegistryName}@PublicationEvaluationCompleted'
      Description: 'The schema for when a property evaluation is completed'
      Content: !Sub |
        {
          "openapi": "3.0.0",
          "info": {
            "version": "1.0.0",
            "title": "PublicationEvaluationCompleted"
          },
          "paths": {},
          "components": {
            "schemas": {
              "AWSEvent": {
                "type": "object",
                "required": [
                  "detail-type",
                  "resources",
                  "detail",
                  "id",
                  "source",
                  "time",
                  "region",
                  "version",
                  "account"
                ],
                "x-amazon-events-detail-type": "PublicationEvaluationCompleted",
                "x-amazon-events-source": "${EventRegistry.RegistryName}",
                "properties": {
                  "detail": {
                    "$ref": "#/components/schemas/PublicationEvaluationCompleted"
                  },
                  "account": {
                    "type": "string"
                  },
                  "detail-type": {
                    "type": "string"
                  },
                  "id": {
                    "type": "string"
                  },
                  "region": {
                    "type": "string"
                  },
                  "resources": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "source": {
                    "type": "string"
                  },
                  "time": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "version": {
                    "type": "string"
                  }
                }
              },
              "PublicationEvaluationCompleted": {
                "type": "object",
                "required": [
                  "property_id",
                  "evaluation_result"
                ],
                "properties": {
                  "property_id": {
                    "type": "string"
                  },
                  "evaluation_result": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
