# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: '2010-09-09'
Description: Defines the rule for the events (subscriptions) that Unicorn Properties wants to consume.

Parameters:
  Stage:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - prod

Resources:

  #### UNICORN CONTRACTS EVENT SUBSCRIPTIONS
  ContractStatusChangedSubscriptionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: unicorn.properties-ContractStatusChanged
      Description: Contract Status Changed subscription
      EventBusName: !Sub "{{resolve:ssm:/uni-prop/${Stage}/UnicornContractsEventBusArn}}"
      EventPattern:
        source:
          - !Sub "{{resolve:ssm:/uni-prop/${Stage}/UnicornContractsNamespace}}"
        detail-type:
          - ContractStatusChanged
      State: ENABLED
      Targets:
        - Id: SendEventTo
          Arn: !Sub "{{resolve:ssm:/uni-prop/${Stage}/UnicornPropertiesEventBusArn}}"
          RoleArn: !GetAtt UnicornPropertiesSubscriptionRole.Arn

  #### UNICORN WEB EVENT SUBSCRIPTIONS
  PublicationApprovalRequestedSubscriptionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: unicorn.properties-PublicationApprovalRequested
      Description: Publication evaluation completed subscription
      EventBusName: !Sub "{{resolve:ssm:/uni-prop/${Stage}/UnicornWebEventBusArn}}"
      EventPattern:
        source:
          - !Sub "{{resolve:ssm:/uni-prop/${Stage}/UnicornWebNamespace}}"
        detail-type:
          - PublicationApprovalRequested
      State: ENABLED
      Targets:
        - Id: SendEventTo
          Arn: !Sub "{{resolve:ssm:/uni-prop/${Stage}/UnicornPropertiesEventBusArn}}"
          RoleArn: !GetAtt UnicornPropertiesSubscriptionRole.Arn


  # This IAM role allows EventBridge to assume the permissions necessary to send events 
  # from the publishing event bus, to the subscribing event bus (UnicornPropertiesEventBusArn)
  UnicornPropertiesSubscriptionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: events.amazonaws.com
      Policies:
        - PolicyName: PutEventsOnUnicornPropertiesEventBus
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource: !Sub "{{resolve:ssm:/uni-prop/${Stage}/UnicornPropertiesEventBusArn}}"

Outputs:
  ContractStatusChangedSubscription:
    Description: Rule ARN for Contract service event subscription
    Value: !GetAtt ContractStatusChangedSubscriptionRule.Arn

  PublicationApprovalRequestedSubscription:
    Description: Rule ARN for Web service event subscription
    Value: !GetAtt PublicationApprovalRequestedSubscriptionRule.Arn
