# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: "2010-09-09"
Description: Defines the rule for the events (subscriptions) that Unicorn Properties wants to consume.

Parameters:
  Stage:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - prod

Resources:
  #### UNICORN CONTRACTS EVENT SUBSCRIPTIONS
  ContractStatusChangedSubscriptionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: unicorn.properties-ContractStatusChanged
      Description: Contract Status Changed subscription
      EventBusName:
        Fn::Sub: "{{resolve:ssm:/uni-prop/${Stage}/UnicornContractsEventBusArn}}"
      EventPattern:
        source:
          - "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"
        detail-type:
          - ContractStatusChanged
      State: ENABLED
      Targets:
        - Id: SendEventTo
          Arn:
            Fn::Sub: "{{resolve:ssm:/uni-prop/${Stage}/UnicornPropertiesEventBusArn}}"
          RoleArn:
            Fn::GetAtt: [ UnicornPropertiesSubscriptionRole, Arn ]

  #### UNICORN WEB EVENT SUBSCRIPTIONS
  PublicationApprovalRequestedSubscriptionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: unicorn.properties-PublicationApprovalRequested
      Description: Publication evaluation completed subscription
      EventBusName:
        Fn::Sub: "{{resolve:ssm:/uni-prop/${Stage}/UnicornWebEventBusArn}}"
      EventPattern:
        source:
          - "{{resolve:ssm:/uni-prop/UnicornWebNamespace}}"
        detail-type:
          - PublicationApprovalRequested
      State: ENABLED
      Targets:
        - Id: SendEventTo
          Arn:
            Fn::Sub: "{{resolve:ssm:/uni-prop/${Stage}/UnicornPropertiesEventBusArn}}"
          RoleArn:
            Fn::GetAtt: [ UnicornPropertiesSubscriptionRole, Arn ]


  # This IAM role allows EventBridge to assume the permissions necessary to send events 
  # from the publishing event bus, to the subscribing event bus (UnicornPropertiesEventBusArn)
  UnicornPropertiesSubscriptionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: events.amazonaws.com
      Policies:
        - PolicyName: PutEventsOnUnicornPropertiesEventBus
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource:
                  Fn::Sub: "{{resolve:ssm:/uni-prop/${Stage}/UnicornPropertiesEventBusArn}}"

Outputs:
  ContractStatusChangedSubscription:
    Description: Rule ARN for Contract service event subscription
    Value:
      Fn::GetAtt: [ ContractStatusChangedSubscriptionRule, Arn ]

  PublicationApprovalRequestedSubscription:
    Description: Rule ARN for Web service event subscription
    Value:
      Fn::GetAtt: [ PublicationApprovalRequestedSubscriptionRule, Arn ]
