# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: '2010-09-09'
Description: Defines the event bus policies that determine who can create rules on the event bus to
  subscribe to events published by the Contracts Service.

Parameters:
  Stage:
    Type: String
    Default: Local
    AllowedValues:
      - Local
      - Dev
      - Prod

Resources:
  # Update this policy as you get new subscribers by adding their namespace to events:source
  CrossServiceCreateRulePolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Sub "{{resolve:ssm:/UniProp/${Stage}/UnicornPropertiesEventBus}}"
      StatementId: !Sub CreateRulePolicy-${Stage}
      Statement:
        Effect: Allow
        Principal:
          AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
        Action:
          - events:PutRule
          - events:DeleteRule
          - events:DescribeRule
          - events:DisableRule
          - events:EnableRule
          - events:PutTargets
          - events:RemoveTargets
        Resource:
          - !Sub
              - arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/${eventBusName}/*
              - eventBusName: !Sub "{{resolve:ssm:/UniProp/${Stage}/UnicornPropertiesEventBus}}"
        Condition:
          StringEqualsIfExists:
            "events:creatorAccount": "${aws:PrincipalAccount}"
          StringEquals:
            "events:source":
              - !Sub "{{resolve:ssm:/UniProp/${Stage}/UnicornContractsNamespace}}"
          "Null":
            "events:source": "false"
