# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: >
  Unicorn Properties Service. Validate the content, images and contract of property listings.

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - ES4000 # Rule disabled because the CatchAll Rule doesn't need a DLQ
        - ES6000 # Rule disabled because SQS DLQs don't need a RedrivePolicy
        - E0001 # Rule disabled because cfn-lint cannot parse SAM Policy templates without arguments (ComprehendBasicAccessPolicy, RekognitionDetectOnlyPolicy)
        - WS2001 # Rule disabled because check does not support !ToJsonString transform
        - ES1001 # Rule disabled because our Lambda functions don't need DestinationConfig.OnFailure
        - W3002 # Rule disabled as nested templates are being packaged 

Parameters:
  Stage:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - prod

Mappings:
  LogsRetentionPeriodMap:
    local:
      Days: 3
    dev:
      Days: 3
    prod:
      Days: 14
  Constants:
    ProjectName:
      Value: "AWS Serverless Developer Experience"

Conditions:
  IsProd: !Equals [!Ref Stage, Prod]

Globals:
  Function:
    Runtime: python3.11
    MemorySize: 128
    Timeout: 15
    Tracing: Active
    Architectures:
      - x86_64
    Environment:
      Variables:
        CONTRACT_STATUS_TABLE: !Ref ContractStatusTable
        EVENT_BUS: !Ref UnicornPropertiesEventBus
        SERVICE_NAMESPACE: "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}"
        POWERTOOLS_LOGGER_CASE: PascalCase
        POWERTOOLS_SERVICE_NAME: "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}"
        POWERTOOLS_TRACE_DISABLED: "false" # Explicitly disables tracing, default
        POWERTOOLS_LOGGER_LOG_EVENT: !If [IsProd, "false", "true"] # Logs incoming event, default
        POWERTOOLS_LOGGER_SAMPLE_RATE: !If [IsProd, "0.1", "0"] # Debug log sampling percentage, default
        POWERTOOLS_METRICS_NAMESPACE: "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}"
        POWERTOOLS_LOG_LEVEL: INFO # Log level for Logger (INFO, DEBUG, etc.), default
        LOG_LEVEL: INFO # Log level for Logger
    Tags:
      stage: !Ref Stage
      project: !FindInMap [Constants, ProjectName, Value]
      namespace: "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}"

Resources:
  #### SSM PARAMETERS
  # Services share their event bus name and arn
  UnicornPropertiesEventBusNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /uni-prop/${Stage}/UnicornPropertiesEventBus
      Value: !GetAtt UnicornPropertiesEventBus.Name

  UnicornPropertiesEventBusArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /uni-prop/${Stage}/UnicornPropertiesEventBusArn
      Value: !GetAtt UnicornPropertiesEventBus.Arn

  #### LAMBDA FUNCTIONS
  # Listens to ContractStatusChanged events from EventBridge
  ContractStatusChangedHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: properties_service.contract_status_changed_event_handler.lambda_handler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref ContractStatusTable
        - DynamoDBReadPolicy:
            TableName: !Ref ContractStatusTable
      Events:
        StatusChangedEvent:
          Type: EventBridgeRule
          Properties:
            RuleName: unicorn.properties-ContractStatusChanged
            EventBusName: !GetAtt UnicornPropertiesEventBus.Name
            Pattern:
              source:
                - "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"
              detail-type:
                - ContractStatusChanged
            RetryPolicy:
              MaximumRetryAttempts: 5
              MaximumEventAgeInSeconds: 900
            DeadLetterConfig:
              Arn: !GetAtt PropertiesEventBusRuleDLQ.Arn
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SQS
            Destination: !GetAtt PropertiesServiceDLQ.Arn

  # Log group for the ContractStatusChangedHandlerFunction
  ContractStatusChangedHandlerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ContractStatusChangedHandlerFunction}"
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  # Listens to Contract status changes from ContractStatusTable to un-pause StepFunctions
  PropertiesApprovalSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: properties_service.properties_approval_sync_function.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ContractStatusTable
        - DynamoDBStreamReadPolicy:
            TableName: !Ref ContractStatusTable
            StreamName:
              !Select [3, !Split ["/", !GetAtt ContractStatusTable.StreamArn]]
        - SQSSendMessagePolicy:
            QueueName: !GetAtt PropertiesServiceDLQ.QueueName
        - Statement:
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
              Resource:
                - !Ref ApprovalStateMachine
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt ContractStatusTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
            MaximumRetryAttempts: 3
            DestinationConfig:
              OnFailure:
                Destination: !GetAtt PropertiesServiceDLQ.Arn
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SQS
            Destination: !GetAtt PropertiesServiceDLQ.Arn

  # Log group for the PropertiesApprovalSyncFunction
  PropertiesApprovalSyncFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PropertiesApprovalSyncFunction}"
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  # Part of the ApprovalStateMachine, checks if a given Property has an existing Contract in ContractStatusTable
  ContractExistsCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: properties_service.contract_exists_checker_function.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ContractStatusTable

  # Log group for the ContractExistsCheckerFunction
  ContractExistsCheckerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ContractExistsCheckerFunction}"
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  # Part of the ApprovalStateMachine, validates if all outputs of content checking steps are OK
  ContentIntegrityValidatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: properties_service.content_integrity_validator_function.lambda_handler

  # Log group for the ContentIntegrityValidatorFunction
  ContentIntegrityValidatorFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ContentIntegrityValidatorFunction}"
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  # Part of the ApprovalStateMachine, pauses the workflow execution and stores token in ContractStatusTable until contract is approved
  WaitForContractApprovalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: properties_service.wait_for_contract_approval_function.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ContractStatusTable

  # Log group for the WaitForContractApprovalFunction
  WaitForContractApprovalFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${WaitForContractApprovalFunction}"
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  #### STATE MACHINE
  ApprovalStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${AWS::StackName}-ApprovalStateMachine"
      DefinitionUri: state_machine/property_approval.asl.yaml
      Tracing:
        Enabled: true
      Policies:
        - AWSXRayDaemonWriteAccess
        - ComprehendBasicAccessPolicy: {}
        - RekognitionDetectOnlyPolicy: {}
        - LambdaInvokePolicy:
            FunctionName: !Ref WaitForContractApprovalFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ContentIntegrityValidatorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ContractExistsCheckerFunction
        - S3ReadPolicy:
            BucketName: !Sub "{{resolve:ssm:/uni-prop/${Stage}/ImagesBucket}}"
        - EventBridgePutEventsPolicy:
            EventBusName: !GetAtt UnicornPropertiesEventBus.Name
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
                - cloudwatch:PutMetricData
              Resource: "*"
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt ApprovalStateMachineLogGroup.Arn
        Level: ALL
        IncludeExecutionData: true
      Events:
        PublicationApprovalRequestedEvent:
          Type: EventBridgeRule
          Properties:
            RuleName: unicorn.properties-PublicationApprovalRequested
            EventBusName: !GetAtt UnicornPropertiesEventBus.Name
            Pattern:
              source:
                - "{{resolve:ssm:/uni-prop/UnicornWebNamespace}}"
              detail-type:
                - PublicationApprovalRequested
            RetryPolicy:
              MaximumRetryAttempts: 5
              MaximumEventAgeInSeconds: 900
            DeadLetterConfig:
              Type: SQS
              Destination: !GetAtt PropertiesServiceDLQ.Arn
      DefinitionSubstitutions:
        ContractExistsChecker: !GetAtt ContractExistsCheckerFunction.Arn
        WaitForContractApproval: !GetAtt WaitForContractApprovalFunction.Arn
        ContentIntegrityValidator: !GetAtt ContentIntegrityValidatorFunction.Arn
        ImageUploadBucketName: !Sub "{{resolve:ssm:/uni-prop/${Stage}/ImagesBucket}}"
        EventBusName: !GetAtt UnicornPropertiesEventBus.Name
        ServiceName: "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}"

  # Store ApprovalStateMachineLogGroup workflow execution logs
  ApprovalStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/states/${AWS::StackName}-ApprovalStateMachine"
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  #### DEAD LETTER QUEUES
  # Store EventBridge events that failed to be DELIVERED to ContractStatusChangedHandlerFunction
  PropertiesEventBusRuleDLQ:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      SqsManagedSseEnabled: true
      MessageRetentionPeriod: 1209600 # Maximum value, 1,209,600 (14days)
      Tags:
        - Key: project
          Value: !FindInMap [Constants, ProjectName, Value]
        - Key: namespace
          Value: "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}"
        - Key: stage
          Value: !Ref Stage

  # Store failed INVOCATIONS to each Lambda function in Unicorn Properties Service
  PropertiesServiceDLQ:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      SqsManagedSseEnabled: true
      MessageRetentionPeriod: 1209600 # Maximum value, 1,209,600 (14days)
      Tags:
        - Key: project
          Value: !FindInMap [Constants, ProjectName, Value]
        - Key: namespace
          Value: "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}"
        - Key: stage
          Value: !Ref Stage

  #### DYNAMODB TABLE
  ContractStatusTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: property_id
          AttributeType: S
      KeySchema:
        - AttributeName: property_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: project
          Value: !FindInMap [Constants, ProjectName, Value]
        - Key: namespace
          Value: "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}"
        - Key: stage
          Value: !Ref Stage

  #### EVENT BUS
  # Event bus for Unicorn Properties Service, used to publish and consume events
  UnicornPropertiesEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub UnicornPropertiesBus-${Stage}

  # Event bus policy to restrict who can publish events (should only be services from UnicornPropertiesNamespace)
  UnicornPropertiesEventsBusPublishPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref UnicornPropertiesEventBus
      StatementId: !Sub OnlyPropertiesServiceCanPublishToEventBus-${Stage}
      Statement:
        Effect: Allow
        Principal:
          AWS:
            - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
        Action: events:PutEvents
        Resource: !GetAtt UnicornPropertiesEventBus.Arn
        Condition:
          StringEquals:
            events:source:
              - "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}"

  # Catchall rule used for development purposes. Logs all events matching any of the services to CloudWatch Logs
  UnicornPropertiesCatchAllRule:
    Type: AWS::Events::Rule
    Properties:
      Name: properties.catchall
      Description: Catchall rule used for development purposes.
      EventBusName: !Ref UnicornPropertiesEventBus
      EventPattern:
        account:
          - !Ref AWS::AccountId
        source:
          - "{{resolve:ssm:/uni-prop/UnicornContractsNamespace}}"
          - "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}"
          - "{{resolve:ssm:/uni-prop/UnicornWebNamespace}}"
      State: ENABLED #You may want to disable this rule in production
      Targets:
        - Arn: !GetAtt UnicornPropertiesCatchAllLogGroup.Arn
          Id: !Sub UnicornPropertiesCatchAllLogGroupTarget-${Stage}

  # CloudWatch log group used to catch all events
  UnicornPropertiesCatchAllLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub
        - "/aws/events/${Stage}/${NS}-catchall"
        - Stage: !Ref Stage
          NS: "{{resolve:ssm:/uni-prop/UnicornPropertiesNamespace}}"
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days]

  # Permissions to allow EventBridge to send logs to CloudWatch
  EventBridgeCloudWatchLogGroupPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: !Sub EvBToCWLogs-${AWS::StackName}
      # Note: PolicyDocument has to be established this way. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-resourcepolicy.html#cfn-logs-resourcepolicy-policydocument
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "delivery.logs.amazonaws.com",
                  "events.amazonaws.com"
                ]
              },
              "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": [
                "${UnicornPropertiesCatchAllLogGroup.Arn}"
              ]
            }
          ]
        }

  #### CLOUDFORMATION NESTED STACKS
  # CloudFormation Stack with the Properties Service Event Registry and Schemas
  EventSchemasStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Location: "integration/event-schemas.yaml"
      Parameters:
        Stage: !Ref Stage

  # CloudFormation Stack with the Cross-service EventBus policy for Properties Service
  SubscriberPoliciesStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    DependsOn:
      - UnicornPropertiesEventBusNameParam
    Properties:
      Location: "integration/subscriber-policies.yaml"
      Parameters:
        Stage: !Ref Stage

  # CloudFormation Stack with the Cross-service EventBus Rules for Properties Service
  SubscriptionsStack:
    Type: AWS::Serverless::Application
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    DependsOn:
      - UnicornPropertiesEventBusArnParam
    Properties:
      Location: "integration/subscriptions.yaml"
      Parameters:
        Stage: !Ref Stage

Outputs:
  #### DYNAMODB OUTPUTS
  ContractStatusTableName:
    Description: DynamoDB table storing contract status information
    Value: !Ref ContractStatusTable

  #### LAMBDA FUNCTIONS OUTPUTS
  ContractStatusChangedHandlerFunctionName:
    Value: !Ref ContractStatusChangedHandlerFunction
  ContractStatusChangedHandlerFunctionArn:
    Value: !GetAtt ContractStatusChangedHandlerFunction.Arn

  PropertiesApprovalSyncFunctionName:
    Value: !Ref PropertiesApprovalSyncFunction
  PropertiesApprovalSyncFunctionArn:
    Value: !GetAtt PropertiesApprovalSyncFunction.Arn

  ContractExistsCheckerFunctionName:
    Value: !Ref ContractExistsCheckerFunction
  ContractExistsCheckerFunctionArn:
    Value: !GetAtt ContractExistsCheckerFunction.Arn

  ContentIntegrityValidatorFunctionName:
    Value: !Ref ContentIntegrityValidatorFunction
  ContentIntegrityValidatorFunctionArn:
    Value: !GetAtt ContentIntegrityValidatorFunction.Arn

  WaitForContractApprovalFunctionName:
    Value: !Ref WaitForContractApprovalFunction
  WaitForContractApprovalFunctionArn:
    Value: !GetAtt WaitForContractApprovalFunction.Arn

  #### STEPFUNCTIONS OUTPUTS
  ApprovalStateMachineName:
    Value: !GetAtt ApprovalStateMachine.Name
  ApprovalStateMachineArn:
    Value: !Ref ApprovalStateMachine

  #### EVENT BRIDGE OUTPUTS
  UnicornPropertiesEventBusName:
    Value: !GetAtt UnicornPropertiesEventBus.Name

  #### CLOUDWATCH LOGS OUTPUTS
  UnicornPropertiesCatchAllLogGroupArn:
    Description: Log all events on the service's EventBridge Bus
    Value: !GetAtt UnicornPropertiesCatchAllLogGroup.Arn

  ApprovalStateMachineLogGroupName:
    Value: !Ref ApprovalStateMachineLogGroup
