# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: "2010-09-09"
Description: 'Event Schemas for use by the Web Service'

Parameters:
  Stage:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - prod

Resources:
  EventRegistry:
    Type: AWS::EventSchemas::Registry
    Properties: 
      Description: 'Event schemas for Unicorn Web'
      RegistryName:
        Fn::Sub: "{{resolve:ssm:/uni-prop/UnicornWebNamespace}}-${Stage}"

  EventRegistryPolicy:
    Type: AWS::EventSchemas::RegistryPolicy
    Properties: 
      RegistryName:
        Fn::GetAtt: EventRegistry.RegistryName
      Policy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowExternalServices
            Effect: Allow
            Principal:
              AWS:
                - Ref: AWS::AccountId
            Action:
              - schemas:DescribeCodeBinding
              - schemas:DescribeRegistry
              - schemas:DescribeSchema
              - schemas:GetCodeBindingSource
              - schemas:ListSchemas
              - schemas:ListSchemaVersions
              - schemas:SearchSchemas
            Resource:
              - Fn::GetAtt: EventRegistry.RegistryArn
              - Fn::Sub: "arn:${AWS::Partition}:schemas:${AWS::Region}:${AWS::AccountId}:schema/${EventRegistry.RegistryName}*"

  PublicationApprovalRequested:
    Type: AWS::EventSchemas::Schema
    Properties:
      Type: 'OpenApi3'
      RegistryName:
        Fn::GetAtt: EventRegistry.RegistryName
      SchemaName:
        Fn::Sub: '${EventRegistry.RegistryName}@PublicationApprovalRequested'
      Description: 'The schema for a request to publish a property'
      Content:
        Fn::Sub: |
          {
            "openapi": "3.0.0",
            "info": {
              "version": "1.0.0",
              "title": "PublicationApprovalRequested"
            },
            "paths": {},
            "components": {
              "schemas": {
                "AWSEvent": {
                  "type": "object",
                  "required": [
                    "detail-type",
                    "resources",
                    "detail",
                    "id",
                    "source",
                    "time",
                    "region",
                    "version",
                    "account"
                  ],
                  "x-amazon-events-detail-type": "PublicationApprovalRequested",
                  "x-amazon-events-source": "${EventRegistry.RegistryName}",
                  "properties": {
                    "detail": {
                      "$ref": "#/components/schemas/PublicationApprovalRequested"
                    },
                    "account": {
                      "type": "string"
                    },
                    "detail-type": {
                      "type": "string"
                    },
                    "id": {
                      "type": "string"
                    },
                    "region": {
                      "type": "string"
                    },
                    "resources": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "source": {
                      "type": "string"
                    },
                    "time": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "version": {
                      "type": "string"
                    }
                  }
                },
                "PublicationApprovalRequested": {
                  "type": "object",
                  "required": [
                    "images",
                    "address",
                    "listprice",
                    "contract",
                    "description",
                    "currency",
                    "property_id",
                    "status"
                  ],
                  "properties": {
                    "address": {
                      "$ref": "#/components/schemas/Address"
                    },
                    "contract": {
                      "type": "string"
                    },
                    "currency": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "images": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "listprice": {
                      "type": "string"
                    },
                    "property_id": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    }
                  }
                },
                "Address": {
                  "type": "object",
                  "required": [
                    "country",
                    "number",
                    "city",
                    "street"
                  ],
                  "properties": {
                    "city": {
                      "type": "string"
                    },
                    "country": {
                      "type": "string"
                    },
                    "number": {
                      "type": "string"
                    },
                    "street": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
