# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Defines the event bus policies that determine who can create rules on the event bus to
  subscribe to events published by Unicorn Web Service.

Parameters:
  Stage:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - prod

Resources:
  # Update this policy as you get new subscribers by adding their namespace to events:source
  CrossServiceCreateRulePolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName:
        Fn::Sub: "{{resolve:ssm:/uni-prop/${Stage}/UnicornWebEventBus}}"
      StatementId:
        Fn::Sub: "OnlyRulesForWebServiceEvents-${Stage}"
      Statement:
        Effect: Allow
        Principal:
          AWS:
            Fn::Sub: "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
        Action:
          - events:PutRule
          - events:DeleteRule
          - events:DescribeRule
          - events:DisableRule
          - events:EnableRule
          - events:PutTargets
          - events:RemoveTargets
        Resource:
          - Fn::Sub:
              - arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/${eventBusName}/*
              - eventBusName:
                  Fn::Sub: "{{resolve:ssm:/uni-prop/${Stage}/UnicornWebEventBus}}"
        Condition:
          StringEqualsIfExists:
            "events:creatorAccount": "${aws:PrincipalAccount}"
          StringEquals:
            "events:source":
              - Fn::Sub: "{{resolve:ssm:/uni-prop/${Stage}/UnicornWebNamespace}}"
          "Null":
            "events:source": "false"
