# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
Description: >
  This template sets up the core infrastructure for Unicorn Web Service, 
  including event-driven communication, schema management, and Amazon EventBridge. 
  It also provides comprehensive logging and monitoring through CloudWatch, 
  an EventBridge Schema Registry for event schema governance, and cross-service 
  event bus policies for rule creation. Additionally, it supports resource sharing 
  across services using SSM parameters and multi-stage deployments with environment-specific 
  log retention and logging levels.

Parameters:
  Stage:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - prod

Mappings:
  LogsRetentionPeriodMap:
    local:
      Days: 3
    dev:
      Days: 3
    prod:
      Days: 14

Conditions:
  IsProd: !Equals [!Ref Stage, prod]

Resources:
  #################################################################################################
  #### SSM PARAMETERS (global variables)
  #################################################################################################

  # Export the event bus name
  WebEventBusName:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /uni-prop/${Stage}/WebEventBus
      Value: !GetAtt WebEventBus.Name

  # Export the event bus ARN
  WebEventBusArn:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /uni-prop/${Stage}/WebEventBusArn
      Value: !GetAtt WebEventBus.Arn

  # Export the Schema registry name
  WebSchemaRegistryName:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /uni-prop/${Stage}/WebSchemaRegistryName
      Value: !GetAtt WebSchemaRegistry.RegistryName

  #################################################################################################
  #### EVENT BUS
  #################################################################################################

  WebEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub unicorn-web-eventbus-${Stage}
      LogConfig:
        IncludeDetail: FULL # [FULL or NONE]
        Level: !If [IsProd, ERROR, INFO] # INFO | ERROR | TRACE | OFF

  #################################################################################################
  #### EVENT BUS POLICIES
  #################################################################################################

  # Event bus policy to restrict who can publish events (should only be services from UnicornWebNamespace)
  WebEventBusPublishPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref WebEventBus
      StatementId: !Sub OnlyWebServiceCanPublishToEventBus-${Stage}
      Statement:
        Effect: Allow
        Principal:
          AWS:
            - !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
        Action: events:PutEvents
        Resource: !GetAtt WebEventBus.Arn
        Condition:
          StringEquals:
            events:source:
              - "{{resolve:ssm:/uni-prop/UnicornWebNamespace}}"

  # This policy defines who can create rules on the event bus. Only principals subscribing to
  # Web Service events can create rule on the bus. No rules without a defined source.
  # In a multi-account environment, add multiple AWS accounts as Principal
  RuleManagementPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref WebEventBus
      StatementId: !Sub "OnlyRulesForWebServiceEvents-${Stage}"
      Statement:
        Effect: Allow
        Principal:
          AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
        Action:
          - events:PutRule
          - events:DeleteRule
          - events:DescribeRule
          - events:DisableRule
          - events:EnableRule
          - events:PutTargets
          - events:RemoveTargets
        Resource: !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/${WebEventBus}/*
        Condition:
          StringEqualsIfExists:
            "events:creatorAccount": "${aws:PrincipalAccount}"
          StringEquals:
            "events:source":
              - "{{resolve:ssm:/uni-prop/UnicornWebNamespace}}"
          "Null":
            "events:source": "false"

  # This IAM role allows EventBridge to assume the permissions necessary to send events
  # to the UnicornWeb event bus
  WebEventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: events.amazonaws.com
      Policies:
        - PolicyName: PutEventsOnWebEventBus
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource: !GetAtt WebEventBus.Arn

  ########################################################################################################
  #### EVENT BUS LOGGING
  #### See (https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-bus-logs.html)
  ########################################################################################################

  # Delivery source for capturing ERROR level logs from the EventBridge event bus
  # This resource defines the source of error logs that will be delivered to CloudWatch
  EventBusErrorDeliverySource:
    Type: AWS::Logs::DeliverySource
    Properties:
      Name: !Sub "${WebEventBus.Name}-ERROR-LOGS-${Stage}"
      LogType: ERROR_LOGS # Captures only error-level events and delivery failures
      ResourceArn: !GetAtt WebEventBus.Arn

  # Delivery source for capturing INFO level logs from the EventBridge event bus
  # This resource defines the source of informational logs including successful event processing
  EventBusInfoDeliverySource:
    Type: AWS::Logs::DeliverySource
    Properties:
      Name: !Sub "${WebEventBus.Name}-INFO-LOGS-${Stage}"
      LogType: INFO_LOGS # Captures informational events and successful deliveries
      ResourceArn: !GetAtt WebEventBus.Arn

  # Delivery destination that specifies where EventBridge logs should be sent
  # This connects the delivery sources to the target CloudWatch Log Group
  EventBusDeliveryDestination:
    Type: AWS::Logs::DeliveryDestination
    Properties:
      Name: !Sub "${WebEventBus.Name}-DeliveryDestination-${Stage}"
      DestinationResourceArn: !GetAtt EventBusLogGroup.Arn # Points to our custom log group

  # Delivery configuration that routes ERROR logs from source to destination
  # This creates the actual log delivery pipeline for error events
  EventBusErrorLoggingDelivery:
    Type: AWS::Logs::Delivery
    DependsOn:
      - EventBusInfoLoggingDelivery
    Properties:
      DeliverySourceName:
        Ref: EventBusErrorDeliverySource # Links to the error log source
      DeliveryDestinationArn: !GetAtt EventBusDeliveryDestination.Arn # Routes to our destination

  # Delivery configuration that routes INFO logs from source to destination
  # This creates the actual log delivery pipeline for informational events
  EventBusInfoLoggingDelivery:
    Type: AWS::Logs::Delivery
    Properties:
      DeliverySourceName:
        Ref: EventBusInfoDeliverySource # Links to the info log source
      DeliveryDestinationArn: !GetAtt EventBusDeliveryDestination.Arn # Routes to our destination

  # CloudWatch Log Group for storing EventBridge event bus logs
  # This is the final destination where all event bus logs are stored and can be queried
  EventBusLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete # Log group will be deleted when stack is updated/replaced
    DeletionPolicy: Delete # Log group will be deleted when stack is deleted
    Properties:
      LogGroupName: !Sub "/aws/vendedlogs/events/event-bus/${WebEventBus.Name}-${Stage}"
      RetentionInDays: !FindInMap [LogsRetentionPeriodMap, !Ref Stage, Days] # Retention varies by environment (3 days for local/dev, 14 days for prod)

  #################################################################################################
  #### SCHEMA REGISTRY
  #################################################################################################
  WebSchemaRegistry:
    Type: AWS::EventSchemas::Registry
    Properties:
      Description: "Event schemas for Unicorn Web"
      RegistryName: !Sub "{{resolve:ssm:/uni-prop/UnicornWebNamespace}}-${Stage}"

  EventRegistryPolicy:
    Type: AWS::EventSchemas::RegistryPolicy
    Properties:
      RegistryName: !GetAtt WebSchemaRegistry.RegistryName
      Policy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowExternalServices
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - schemas:DescribeCodeBinding
              - schemas:DescribeRegistry
              - schemas:DescribeSchema
              - schemas:GetCodeBindingSource
              - schemas:ListSchemas
              - schemas:ListSchemaVersions
              - schemas:SearchSchemas
            Resource:
              - !GetAtt WebSchemaRegistry.RegistryArn
              - !Sub "arn:${AWS::Partition}:schemas:${AWS::Region}:${AWS::AccountId}:schema/${WebSchemaRegistry.RegistryName}*"

Outputs:
  WebEventBusName:
    Description: "Name of the Unicorn Web Event Bus"
    Value: !Ref WebEventBus
  WebEventBusArn:
    Description: "ARN of the Unicorn Web Event Bus"
    Value: !GetAtt WebEventBus.Arn

  # CloudWatch Log Group Outputs
  WebEventHandlerFunctionLogGroupName:
    Description: "Name of the Web Event Handler Function Log Group"
    Value: !Ref EventBusLogGroup
  WebEventHandlerFunctionLogGroupArn:
    Description: "ARN of the Web Event Handler Function Log Group"
    Value: !GetAtt EventBusLogGroup.Arn

  # Schema Registry Outputs
  WebSchemaRegistryName:
    Description: "Name of the Unicorn Web Schema Registry"
    Value: !Ref WebSchemaRegistry

  WebSchemaRegistryArn:
    Description: "ARN of the Unicorn Web Schema Registry"
    Value: !GetAtt WebSchemaRegistry.RegistryArn

  # Exporting this role so it can be referenced across Approval subscriptions
  # This is not a global variable, so not sharing as a SSM parameter.
  WebEventBridgeRoleArn:
    Description: "ARN of the Unicorn Web EventBridge Role"
    Value: !GetAtt WebEventBridgeRole.Arn
    Export:
      Name: !Sub "uni-prop-${Stage}-web-domain-EventBridgeRoleArn"
