version: 0.1

default:
  global:
    parameters:
      stack_name: uni-prop-local-shared
      s3_prefix: uni-prop-local-shared
      resolve_s3: true
  deploy:
    parameters:
      template_file: uni-prop-shared.yaml
      confirm_changeset: false
      fail_on_empty_changeset: false
      on_failure: ROLLBACK
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - "Stage=local"
