AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Shared namespace configuration for the Unicorn Properties microservices architecture.
  This template establishes centralized namespace parameters stored in AWS Systems Manager
  Parameter Store, enabling consistent service identification and cross-service communication
  across the Contracts, Approvals, and Web services. Deploy this template once per environment
  before deploying individual microservices to ensure proper namespace resolution.

Resources:
  UnicornContractsNamespaceParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /uni-prop/UnicornContractsNamespace
      Value: "unicorn-contracts"

  UnicornApprovalsNamespaceParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /uni-prop/UnicornApprovalsNamespace
      Value: "unicorn-approvals"

  UnicornWebNamespaceParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /uni-prop/UnicornWebNamespace
      Value: "unicorn-web"

Outputs:
  UnicornContractsNamespace:
    Description: Unicorn Contracts namespace parameter
    Value: !Ref UnicornContractsNamespaceParam

  UnicornApprovalsNamespace:
    Description: Unicorn Properties namespace parameter
    Value: !Ref UnicornApprovalsNamespaceParam

  UnicornWebNamespace:
    Description: Unicorn Web namespace parameter
    Value: !Ref UnicornWebNamespaceParam

  UnicornContractsNamespaceVale:
    Description: Unicorn Contracts namespace parameter value
    Value: !GetAtt UnicornContractsNamespaceParam.Value

  UnicornApprovalsNamespaceValue:
    Description: Unicorn Properties namespace parameter value
    Value: !GetAtt UnicornApprovalsNamespaceParam.Value

  UnicornWebNamespaceValue:
    Description: Unicorn Web namespace parameter value
    Value: !GetAtt UnicornWebNamespaceParam.Value
