# coding: utf-8

from __future__ import absolute_import

from schema.unicorn_properties_web.publicationapprovalrequested.marshaller import Marshaller
from schema.unicorn_properties_web.publicationapprovalrequested.AWSEvent import AWSEvent
from schema.unicorn_properties_web.publicationapprovalrequested.PublicationApprovalRequested import PublicationApprovalRequested
